# Generated by Django 6.0.1 on 2026-01-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Proyecto')),
                ('tema', models.CharField(max_length=100, verbose_name='Tema (ej: App Ventas, IA)')),
                ('descripcion', models.TextField(verbose_name='Descripción Breve')),
                ('imagen', models.ImageField(upload_to='proyectos/', verbose_name='Imagen del Proyecto')),
                ('enlace', models.URLField(blank=True, null=True, verbose_name='Enlace al Proyecto (Deploy)')),
                ('fecha', models.DateField(verbose_name='Fecha de Realización')),
                ('tecnologias', models.CharField(max_length=200, verbose_name='Tecnologías')),
                ('repositorio', models.URLField(blank=True, null=True, verbose_name='Enlace al Repo (GitHub)')),
                ('publicado', models.BooleanField(default=True, verbose_name='¿Visible?')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha'],
            },
        ),
    ]
